2023-05-18 15:18:35,444 case_execute INFO read_file.py [line:86] 开始读取测试用例文件
2023-05-18 15:18:35,445 case_execute INFO read_file.py [line:88] 执行的用例文件为:['testdata/login/login.yaml']
2023-05-18 15:18:35,457 case_execute INFO replace.py [line:18] 提取用例标识符,提取的标识符列表为:[]
2023-05-18 15:18:35,457 case_execute INFO requests.py [line:31] 开始请求api/v1/pub/login/3rd接口
2023-05-18 15:18:45,537 case_execute ERROR requests.py [line:36] 请求失败，错误信息为HTTPSConnectionPool(host='ud3test.unity-drive.net', port=443): Max retries exceeded with url: /api/v1/pub/login/3rd (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x00000156B25A34F0>: Failed to establish a new connection: [Errno 11002] getaddrinfo failed'))
2023-05-18 15:18:45,977 case_execute INFO replace.py [line:18] 提取用例标识符,提取的标识符列表为:[]
2023-05-18 15:18:45,977 case_execute INFO requests.py [line:31] 开始请求api/v1/pub/login/3rd接口
2023-05-18 15:18:45,980 case_execute ERROR requests.py [line:36] 请求失败，错误信息为HTTPSConnectionPool(host='ud3test.unity-drive.net', port=443): Max retries exceeded with url: /api/v1/pub/login/3rd (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x00000156B2FF50A0>: Failed to establish a new connection: [Errno 11002] getaddrinfo failed'))
2023-05-18 15:19:19,885 case_execute INFO read_file.py [line:86] 开始读取测试用例文件
2023-05-18 15:19:19,886 case_execute INFO read_file.py [line:88] 执行的用例文件为:['testdata/login/login.yaml']
2023-05-18 15:19:19,895 case_execute INFO replace.py [line:18] 提取用例标识符,提取的标识符列表为:[]
2023-05-18 15:19:19,895 case_execute INFO requests.py [line:31] 开始请求api/v1/pub/login/3rd接口
2023-05-18 15:19:20,022 case_execute INFO requests.py [line:33] 接口请求成功
2023-05-18 15:19:20,024 case_execute INFO assertUtil.py [line:32] 开始断言预期结果与实际结果是否相等。
2023-05-18 15:19:20,024 case_execute INFO assertUtil.py [line:53] 断言结果列表:[True]
2023-05-18 15:19:20,024 case_execute INFO assertUtil.py [line:54] 用例断言成功！
2023-05-18 15:19:20,036 case_execute INFO test_case.py [line:21] 用例名称:用户登录成功,该用例属于testdata/login/login.yaml文件
2023-05-18 15:19:20,059 case_execute INFO replace.py [line:18] 提取用例标识符,提取的标识符列表为:[]
2023-05-18 15:19:20,061 case_execute INFO requests.py [line:31] 开始请求api/v1/pub/login/3rd接口
2023-05-18 15:19:20,142 case_execute INFO requests.py [line:33] 接口请求成功
2023-05-18 15:19:20,142 case_execute INFO assertUtil.py [line:32] 开始断言预期结果与实际结果是否相等。
2023-05-18 15:19:20,142 case_execute INFO assertUtil.py [line:53] 断言结果列表:[True]
2023-05-18 15:19:20,142 case_execute INFO assertUtil.py [line:54] 用例断言成功！
2023-05-18 15:19:20,147 case_execute INFO test_case.py [line:21] 用例名称:用户登录成功1,该用例属于testdata/login/login.yaml文件
2023-05-18 15:47:38,065 case_execute INFO read_file.py [line:86] 开始读取测试用例文件
2023-05-18 15:47:38,065 case_execute INFO read_file.py [line:88] 执行的用例文件为:['testdata/login/login.yaml']
2023-05-18 15:47:38,078 case_execute INFO replace.py [line:18] 提取用例标识符,提取的标识符列表为:[]
2023-05-18 15:47:38,079 case_execute INFO requests.py [line:43] 开始请求api/v1/pub/login/3rd接口
2023-05-18 15:47:38,284 case_execute INFO requests.py [line:45] 接口请求成功
2023-05-18 15:47:38,285 case_execute INFO assertUtil.py [line:32] 开始断言预期结果与实际结果是否相等。
2023-05-18 15:47:38,286 case_execute INFO assertUtil.py [line:53] 断言结果列表:[True]
2023-05-18 15:47:38,286 case_execute INFO assertUtil.py [line:54] 用例断言成功！
2023-05-18 15:47:38,299 case_execute INFO test_case.py [line:21] 用例名称:用户登录成功,该用例属于testdata/login/login.yaml文件
2023-05-18 15:47:38,324 case_execute INFO replace.py [line:18] 提取用例标识符,提取的标识符列表为:[]
2023-05-18 15:47:38,325 case_execute INFO requests.py [line:43] 开始请求api/v1/pub/login/3rd接口
2023-05-18 15:47:38,446 case_execute INFO requests.py [line:45] 接口请求成功
2023-05-18 15:47:38,447 case_execute INFO assertUtil.py [line:32] 开始断言预期结果与实际结果是否相等。
2023-05-18 15:47:38,447 case_execute INFO assertUtil.py [line:53] 断言结果列表:[True]
2023-05-18 15:47:38,447 case_execute INFO assertUtil.py [line:54] 用例断言成功！
2023-05-18 15:47:38,460 case_execute INFO test_case.py [line:21] 用例名称:用户登录成功1,该用例属于testdata/login/login.yaml文件
2023-05-18 16:10:11,868 case_execute INFO read_file.py [line:86] 开始读取测试用例文件
2023-05-18 16:10:11,868 case_execute INFO read_file.py [line:88] 执行的用例文件为:['testdata/login/login.yaml']
2023-05-18 16:10:11,875 case_execute INFO replace.py [line:18] 提取用例标识符,提取的标识符列表为:[]
2023-05-18 16:10:11,875 case_execute INFO requests.py [line:43] 开始请求api/v1/pub/login/3rd接口
2023-05-18 16:10:11,986 case_execute INFO requests.py [line:45] 接口请求成功
2023-05-18 16:10:11,986 case_execute INFO assertUtil.py [line:32] 开始断言预期结果与实际结果是否相等。
2023-05-18 16:10:11,986 case_execute INFO assertUtil.py [line:53] 断言结果列表:[True]
2023-05-18 16:10:11,986 case_execute INFO assertUtil.py [line:54] 用例断言成功！
2023-05-18 16:10:11,990 case_execute INFO test_case.py [line:21] 用例名称:用户登录成功,该用例属于testdata/login/login.yaml文件
2023-05-18 16:10:11,995 case_execute INFO replace.py [line:18] 提取用例标识符,提取的标识符列表为:[]
2023-05-18 16:10:11,996 case_execute INFO requests.py [line:43] 开始请求api/v1/pub/login/3rd接口
2023-05-18 16:10:12,110 case_execute INFO requests.py [line:45] 接口请求成功
2023-05-18 16:10:12,110 case_execute INFO assertUtil.py [line:32] 开始断言预期结果与实际结果是否相等。
2023-05-18 16:10:12,110 case_execute INFO assertUtil.py [line:53] 断言结果列表:[True]
2023-05-18 16:10:12,110 case_execute INFO assertUtil.py [line:54] 用例断言成功！
2023-05-18 16:10:12,113 case_execute INFO test_case.py [line:21] 用例名称:用户登录成功1,该用例属于testdata/login/login.yaml文件
